# Generated by Django 3.0.7 on 2020-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0002_auto_20201017_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='date',
            field=models.DateField(help_text='Day the Squirrel was Sighted', null=True),
        ),
    ]
