# Generated by Django 3.0.7 on 2020-10-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0004_auto_20201017_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Day the Squirrel was Sighted', null=True),
        ),
    ]
