# Generated by Django 3.1.2 on 2020-10-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0005_auto_20201017_2113'),
        ('squirrels', '0004_auto_20201017_2147'),
    ]

    operations = [
    ]
