# Generated by Django 3.1.2 on 2020-10-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0006_merge_20201018_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Day the Squirrel was Sighted', null=True),
        ),
        migrations.DeleteModel(
            name='Sighting',
        ),
    ]
