# Generated by Django 3.0.7 on 2020-10-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0007_auto_20201018_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(help_text='Day the Squirrel was Sighted', null=True),
        ),
    ]
