# Generated by Django 3.0.7 on 2020-10-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0008_auto_20201019_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '?')], default='Adult', help_text='How old was this squirrel', max_length=20),
        ),
    ]
