# Generated by Django 3.0.7 on 2020-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0010_auto_20201021_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '?')], default='Adult', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
